# Generated by Django 5.2.3 on 2025-07-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuprimerapagina', '0002_curso_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='familiar',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='fecha_inscripcion',
            new_name='fecha_nacimiento',
        ),
    ]
