# Generated by Django 5.2.3 on 2025-07-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuprimerapagina', '0003_profesor_delete_familiar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
